Iter15: added concurrent handler for deleting urls
Makovey/shortener pull request #15
Opened 2024-11-26 13:45 UTC by Makovey

2024-12-03 02:50 UTC, bulbetski requested changes
Написано в целом хорошо, в основном замечания по неймингу и работе с бд.

2024-12-03 02:50 UTC, bulbetski commented on internal/api/shortenerapi/handler.go
> +	if userID == "" {
Стоит так же сразу проверять формат user_id. Мало ли что там за кал прилетит

2024-12-03 02:50 UTC, bulbetski commented on internal/api/shortenerapi/handler.go
> +		h.writeResponseWithError(w, http.StatusUnauthorized, "unauthorized")
Это ошибка BadRequest

2024-12-03 02:50 UTC, bulbetski commented on internal/api/shortenerapi/handler.go
>  		h.writeResponse(w, http.StatusBadRequest, err.Error())
Здесь у нас Internal -- мы накосячили, либо NotFound -- мы не нашли. BadRequest это когда клиент нам отправил херню и мы ничего не можем с ней сделать.

2024-12-03 02:50 UTC, bulbetski commented on internal/api/shortenerapi/handler.go
> +		h.writeResponseWithError(w, http.StatusUnauthorized, "unauthorized")
Исправить нужно везде, где такая песня

2024-12-03 02:50 UTC, bulbetski commented on internal/api/shortenerapi/handler.go
> +		w.WriteHeader(http.StatusNoContent)
Не очень очевидно, что пустой массив это успех. Действительно ли это так?

2024-12-03 02:50 UTC, bulbetski commented on internal/api/shortenerapi/handler.go
> +	var ids []string
Если массив ids пустой, мы все равно вызываем DeleteUsersURLS, что может быть излишне

2024-12-03 02:50 UTC, bulbetski commented on internal/api/shortenerapi/handler.go
> +	}
Все ошибки удаления просто логируются, но клиенту не возвращается информация о том, какие операции были выполнены успешно, а какие — нет. Даже в случае 100% ошибок, мы возвращаем успешный код, что тоже некорректно

2024-12-03 02:50 UTC, bulbetski commented on internal/middleware/jwt.go
> +	secretKey         = "JWT_SECRET" // TODO: replace to env
нужно выполнить тудушку

2024-12-03 02:50 UTC, bulbetski commented on internal/middleware/jwt.go
> +func (j JWTHandler) JWTHandler(next http.Handler) http.Handler {
Обработчик JWTHandler отвечает за множество задач: чтение куки, проверку токена, создание нового токена и обработку контекста. Это нарушает принцип единственной ответственности. Стоит разделить логику на отдельные функции или методы, например, отдельный метод для работы с куками, валидации токенов и создания токенов

2024-12-03 02:50 UTC, bulbetski commented on internal/middleware/jwt.go
> +		if isCookieAbsent && r.URL.Path == "/api/user/urls" {
Логика проверки пути (if isCookieAbsent && r.URL.Path == "/api/user/urls") жёстко закодирована. Это делает обработчик менее универсальным. Можно передавать проверяемые пути как параметр или конфигурацию

2024-12-03 02:50 UTC, bulbetski commented on internal/middleware/jwt.go
> +			userID = uuid.NewString()[:6]
Генерация userID как обрезанного UUID потенциально может привести к коллизиям.
Почему бы просто не использовать полный uuid?

2024-12-03 02:50 UTC, bulbetski commented on internal/middleware/jwt.go
> +}
Как общепринятое правило. Сначала пишем структуру, потом ее конструктор, а потом все методы этой структуры. В сервисе так же можно сделать

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/disc/shortener.go
> +func (r *repo) Get(shortURL, userID string) (repoModel.ShortenGet, error) {
Все методы стоит называть описательно. Действие + назание сущности, над которой это действие производится.
GetFullURL, GetLongURL итд
Касается всех методов.
Так же методы можно называть действиями -- сократить URL -- ShortenURL

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/model/shortenGet.go
> +type ShortenGet struct {
файл надо переименовать, принято называть файлы в snake_case

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/model/shortenGet.go
> +type ShortenGet struct {
название структуры не соответствует действительно и не должно содержать действий. Если эта структура является dbo для твоего репозитория, возьмем как частный случай таблицу Postgres, то она должна называться как сущность в твоей базе. Например просто url. Можно придумать что-то в духе UserURL и так далее

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
>  		if strings.Contains(err.Error(), "duplicate key value violates unique constraint") {
Ошибки стоит сравнивать через errors.Is, скорее всего такая ошибка есть в пакете sql или pgconn.

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
>  	defer stmt.Close()
Если PrepareContext возвращает ошибку, ресурс stmt не создается, но defer stmt.Close() все равно выполнится

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +		INSERT INTO shortener (short_url, original_url, owner_user_id) VALUES ($1, $2, $3)
В запросе можно использовать ON CONFLICT, тогда вместо генерации ошибки дублирования, сервер базы данных сразу выполнит альтернативное действие (может заменить запись или ничего не делать). В таком случае нам не придется проверять ошибки на уровне приложения для обработки дублирующих записей

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +		SELECT original_url, is_deleted FROM shortener WHERE short_url = $1
таблица называется short_url, но мы в ней храним полный url

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +func (r *repo) Get(shortURL, userID string) (repoModel.ShortenGet, error) {
параметр userID не используется

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +	stmt, err := r.db.PrepareContext(ctx, `
PrepareContext используется для запроса, который вызывается один раз. Это избыточно, так как подготовка запроса добавляет лишнюю нагрузку. Можно использовать QueryRowContext напрямую.

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
>  	for _, m := range models {
Если массив models пуст, tx.PrepareContext всё равно выполняется, хотя он не нужен. Стоит добавить проверку на пустой массив models до подготовки запроса.

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +	stmt, err := tx.PrepareContext(ctx, `INSERT INTO shortener (short_url, original_url, owner_user_id) VALUES ($1, $2, $3)`)
Можно обработать конфликты при помощи on conflict

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +		_, err = stmt.ExecContext(ctx, m.ShortURL, m.OriginalURL, userID)
Каждый вызов ExecContext создает отдельный запрос к базе данных, что увеличивает накладные расходы на установление соединения, обработку запроса и его выполнение. При большом количестве данных это получается сильно накладно. Нужно всегда пытаться избегать такой ситуации и делать одиночный insert (либо несколько, но большими батчами).
Можно попробовать написать хэлпер, который будет делать запрос следующего вида
```
VALUES ($1, $2, $3), ($4, $5, $6), ...
```
Либо возможность библиотекой по типу https://github.com/Masterminds/squirrel

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/model/shortenGet.go
> +package model
В каждом методе создается свой контекст. Это не лучшая практика, стоит пробрасывать контекст снаружи и оборачивать его (например, таймаутом) внутри. Контекст будет проходить по всем методам начиная с обработчика хттп запроса.

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +	stmt, err := r.db.PrepareContext(ctx, `SELECT short_url, original_url FROM shortener WHERE owner_user_id = $1`)
Можно QueryContext напрямую

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +		return []model.ShortenBatch{}, err
При ошибках лучше возвращать nil, err

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +func (r *repo) DeleteUsersURL(ctx context.Context, userID string, url string) error {
в этом методе не нужна транзакция. 1 update и так выполняется атомарно

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +func (r *repo) DeleteUsersURL(ctx context.Context, userID string, url string) error {
tx.Rollback вызывается вручную только при ошибке, но не гарантируется выполнение при панике. Нужно гарантировать вызов tx.Rollback через defer, чтобы обработать все возможные случаи

2024-12-03 02:50 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +	stmt, err := tx.PrepareContext(ctx, `
Стоит заменить на ExecContext, т.к. выполняем всего 1 раз

2024-12-03 02:50 UTC, bulbetski commented on internal/service/repository.go
> +	DeleteUsersURL(ctx context.Context, userID string, url string) error
Store → SaveUserURLs
Get → GetFullURL
GetAll → GetUserURLs
DeleteUsersURL → MarkURLAsDeleted

2024-12-03 02:50 UTC, bulbetski commented on internal/service/shortener/service.go
> +func (s *service) Short(url, userID string) (string, error) {
short => shorten
заменяем прилагательное на глагол/действие

2024-12-03 02:50 UTC, bulbetski commented on internal/service/shortener/service.go
>  	shortURL := s.generateShortURL(url)[:7]
[:7] стоит занести внутрь generateShortURL. Так же стоит помнить, что сокращение хэша может привести к коллизиями. В случае коллизии надо повторно генерирровать хэш.

2024-12-03 02:50 UTC, bulbetski commented on internal/service/shortener/service.go
> +func (s *service) Get(shortURL, userID string) (repoModel.ShortenGet, error) {
GetFullURL, более информативно

2024-12-03 02:50 UTC, bulbetski commented on internal/service/shortener/service.go
> +func (s *service) Get(shortURL, userID string) (repoModel.ShortenGet, error) {
Ты правильно разделил сервис на слои, но тогда стоит также разделять и сущности dbo и dto. 
В соседнем методе ты возвращаешь model.ShortenBatchResponse, что корректно, а этом сущность бд.
Либо стоит создать отдельную сущность для ответа сервиса, либо везде использовать models (в репозитории и в сервисе)

2024-12-03 02:50 UTC, bulbetski commented on internal/service/shortener/service.go
> +		models[i].ShortURL = fmt.Sprintf("%s/%s", s.cfg.BaseReturnedURL(), models[i].ShortURL)
не хотим хранить короткий урл, чтобы туда-сюда не конрветировать?

2024-12-03 02:50 UTC, bulbetski commented on internal/service/shortener/service.go
> +		errors := make(chan error)
Слайс errors создается с длиной, равной len(errorsCh), но len(errorsCh) всегда будет 0, так как канал пуст на момент инициализации. Это приводит к добавлению nil значений в слайс, из-за чего итоговый результат может быть неверным. Стоит инициализировать пустой слайс и использовать append для добавления ошибок

2024-12-03 02:50 UTC, bulbetski commented on internal/service/utils/async.go
> +func FanOut[T any](ctx context.Context, numWorkers int, work func(ctx context.Context) chan T) []chan T {
FanOut — это паттерн, используемый для распределения задач из общего источника (например, канала) между несколькими воркерами. Инициатива хорошая, но есть недсоататки:
1. Метод work(ctx) вызывается для каждого воркера, что приводит к созданию множества независимых каналов. Это избыточно, если воркеры работают с общими данными
2. Отсутствие общего входного канала делает сложным управление задачами и синхронизацию между воркерами
3. После завершения работы воркеров нет механизма для ожидания завершения всех задач или обработки ошибок.

Как стоит сделать:
1. Все задачи поступают в один входной канал, который передается всем воркерам.
2. Каждый воркер получает данные из входного канала и выполняет переданную ему функцию.
3. Используетм sync.WaitGroup для ожидания завершения работы всех воркеров.

2024-12-03 02:50 UTC, bulbetski commented on internal/service/utils/async.go
> +	finalCh := make(chan T)
Можно добавить буферизацию, чтобы не блокироваться при большом потоке данных

2024-12-03 14:21 UTC, Makovey commented on internal/api/shortenerapi/handler.go
> +	if userID == "" {
Ниже есть проверка на то, что это строка, добавил еще проверку на длину

2024-12-03 14:45 UTC, Makovey commented on internal/api/shortenerapi/handler.go
>  		h.writeResponse(w, http.StatusBadRequest, err.Error())
Согласен, но это требование учебника.
Спринт 1, Итерация 1:
"На любой некорректный запрос сервер должен возвращать ответ с кодом 400."
На это есть тесты и они фейлятся если изменить статус-код

2024-12-03 14:46 UTC, Makovey commented on internal/api/shortenerapi/handler.go
> +		w.WriteHeader(http.StatusNoContent)
Требование из учебника:
Спринт 4, Инкремент 14:
"При отсутствии сокращённых пользователем URL хендлер должен отдавать HTTP-статус 204 No Content."

2024-12-03 14:50 UTC, Makovey commented on internal/api/shortenerapi/handler.go
> +	}
Согласен, выглядит не очень, но это требование из учебника:
Спринт 4, Инкремент 15:
"В случае успешного приёма запроса хендлер должен возвращать HTTP-статус 202 Accepted. Фактический результат удаления может происходить позже — оповещать пользователя об успешности или неуспешности не нужно."

2024-12-03 14:51 UTC, Makovey commented on internal/middleware/jwt.go
> +	secretKey         = "JWT_SECRET" // TODO: replace to env
Точно, саму тудушку выполнил, но не потер :с

2024-12-03 14:56 UTC, Makovey commented on internal/middleware/jwt.go
> +		if isCookieAbsent && r.URL.Path == "/api/user/urls" {
Согласен, но это костыль для прохождения теста, именно для этой ручки, при отсутствии куки (не только userID как написано в задании) мы должны вернуть 401, для остальных, при отсутствие куки, мы должны сгенерить новую куку.
Спринт 4, Инкремент 14:
"Если кука не содержит ID пользователя, хендлер должен возвращать HTTP-статус 401 Unauthorized."

2024-12-03 14:57 UTC, Makovey commented on internal/middleware/jwt.go
> +			userID = uuid.NewString()[:6]
Согласен, нужны были короткие для дебага, так и прижилось, правлю.

2024-12-03 15:14 UTC, Makovey commented on internal/middleware/jwt.go
> +}
Принял, спасибо, меняю

2024-12-03 16:17 UTC, Makovey commented on internal/middleware/jwt.go
> +func (j JWTHandler) JWTHandler(next http.Handler) http.Handler {
Вынес работу с jwt в отдельный файл с утилсами

2024-12-03 16:40 UTC, Makovey commented on internal/repository/postgres/shortener.go
>  		if strings.Contains(err.Error(), "duplicate key value violates unique constraint") {
Именно такой ошибки нет, но привязался к айди ошибки (в гугле все так делают лол)

2024-12-03 17:09 UTC, Makovey commented on internal/repository/postgres/shortener.go
> +		SELECT original_url, is_deleted FROM shortener WHERE short_url = $1
Таблица - shortener (как сам сервис), а там мы храним и полный и короткий урл

2024-12-03 17:30 UTC, Makovey commented on internal/repository/postgres/shortener.go
> +func (r *repo) Get(shortURL, userID string) (repoModel.ShortenGet, error) {
Для обратной совместимости, если я его заиспользую тут как фильтр, то тесты с прошлых инкрементов, а именно из 12-го, не пройдут, где не было аутентификации

2024-12-03 17:32 UTC, Makovey commented on internal/repository/postgres/shortener.go
> +	stmt, err := r.db.PrepareContext(ctx, `
Идея была в том, чтобы уже был подготовленный запрос для будущих запросов. Удолю

2024-12-03 17:42 UTC, Makovey commented on internal/repository/postgres/shortener.go
>  	for _, m := range models {
Есть проверка на уровне получения запроса, тут тоже тогда добавлю

2024-12-03 18:09 UTC, Makovey commented on internal/repository/postgres/shortener.go
>  	defer stmt.Close()
Сколько не гуглил, вроде легально. Можно, конечно, в ручную закрыть после `Exec`, но в случае с паникой тогда код туда может не дойти.
Как тогда лучше поступить?

2024-12-03 18:14 UTC, Makovey commented on internal/repository/postgres/shortener.go
> +func (r *repo) DeleteUsersURL(ctx context.Context, userID string, url string) error {
Интересный трюк с rollback'ом после коммита, поправил

2024-12-03 18:16 UTC, Makovey commented on internal/repository/postgres/shortener.go
> +		INSERT INTO shortener (short_url, original_url, owner_user_id) VALUES ($1, $2, $3)
Да, было бы удобно. Но по условию задания мы должны отслеживать конфликты, чтобы в случае возникновения вернуть 409 статус код

2024-12-04 07:40 UTC, Makovey commented on internal/service/shortener/service.go
> +		models[i].ShortURL = fmt.Sprintf("%s/%s", s.cfg.BaseReturnedURL(), models[i].ShortURL)
А мы храним оба урла, тут дело в том, что есть еще дополнительный флаг, который возвращает хост для коротких урлов и он может менятся, поэтому его не сторим в базе.

2024-12-04 08:05 UTC, Makovey commented on internal/service/shortener/service.go
> +		errors := make(chan error)
Спасибо, значит `len(errorsCh)` и правда имеет не много смысла, но не понятно в чем проблема.
Если создастся слайс с нулевой длиной, то как это приведет к добавлению `nil` в значения?
На всякий случай заменил `len(errorsCh)` на 0

2024-12-04 08:10 UTC, Makovey commented on internal/service/shortener/service.go
> +func (s *service) Get(shortURL, userID string) (repoModel.ShortenGet, error) {
Да, ты прав, был вопрос на повестке с сущностями.
Меняю

2024-12-04 08:53 UTC, Makovey commented on internal/service/utils/async.go
> +func FanOut[T any](ctx context.Context, numWorkers int, work func(ctx context.Context) chan T) []chan T {
Это нас так в учебнике научили :harold-pain:
Исправляю

2024-12-07 12:06 UTC, bulbetski commented on internal/middleware/jwt.go
> +func (j JWTHandler) JWTHandler(next http.Handler) http.Handler {
Можно не utils, а pkg/jwt

2024-12-07 12:10 UTC, bulbetski commented on internal/repository/postgres/shortener.go
>  	defer stmt.Close()
я какую-то херню написал)))

2024-12-07 12:11 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +		INSERT INTO shortener (short_url, original_url, owner_user_id) VALUES ($1, $2, $3)
а, ну тогда оставляй, как есть

2024-12-07 12:13 UTC, bulbetski commented on internal/repository/postgres/shortener.go
> +func (r *repo) Get(shortURL, userID string) (repoModel.ShortenGet, error) {
так а в сигнатуре репозиторного метода он зачем? чем тебе сигнатура метода совместимость рушит? Просто где-нибудь выше его игнорируй

2024-12-07 12:26 UTC, bulbetski commented on internal/service/utils/async.go
> +func FanOut[T any](ctx context.Context, numWorkers int, work func(ctx context.Context) chan T) []chan T {
>Если делать всё через FanOut и FanIn, не нужен ли только один общий канал?

Да, верно. В большинстве случаев, когда есть общий источник задач (например, массив данных), логичнее использовать один общий канал задач. Воркеры просто обрабатывают задачи из него, а результаты отправляются обратно в один канал.

2024-12-07 12:28 UTC, bulbetski commented on internal/service/utils/async.go
> +func FanOut[T any](ctx context.Context, numWorkers int, work func(ctx context.Context) chan T) []chan T {
Резюмирую:
Почему воркер пул лучше:
Простота. Меньше каналов, меньше точек отказа.
Эффективность. Используется один канал для задач и один канал для результатов, без дублирования.

Использовать FanOut и FanIn имеет смысл, если действительно есть несколько независимых потоков данных.
Для обработки задач из одного источника (например, массива данных) лучше использовать один общий канал задач и распараллеливать работу через горутины.

2024-12-07 12:37 UTC, Makovey commented on internal/middleware/jwt.go
> +func (j JWTHandler) JWTHandler(next http.Handler) http.Handler {
Так и сделаю в следующем проекте

2024-12-07 12:37 UTC, Makovey commented on internal/service/utils/async.go
> +func FanOut[T any](ctx context.Context, numWorkers int, work func(ctx context.Context) chan T) []chan T {
Спасибо за инфо, принял к сведению

2024-12-07 12:38 UTC, merged